travis:
  secure:
    BINSTAR_TOKEN: ZchO4HGmz04MvJE8rzfdWxorjx+yD04IhavGSBT1q1NmcvTbsC743D8uYVDPdSjJ9pdjL/4kXfK0rk4MvrOfaZV+yE0X0bmWyiLVhqjs6I1lfEDox+fpkaOK6SOg2P7xUijaEp6e/Kgcu2/5Dulr32rtua92tuuFV8dMcZIJ5LzwDXCc2oyZeN0zsCYrBKUsRcgAP5HIZDjYxGRhaKasFj9wSlqa0MN7656R+zmjsQJVKNkeS/sqMzp1hDqGDESM1NR1PFJocQPiwG8y+MMckc4lCx1gu/k9ccKj16DnMUujNZrRBFftOp0KeOjah0SGrU3fWN77ybieOgHLArM2DcNkHJXwKIPfnvrPuRAPsOuHIHb/eko3OD8RBcpEh2QcgOgz5gMyPNzTXqbtZwh4ZHI2R48idU516lV5rhU6ZMo7thUoUT8sBDEl62nxio2IRhgyKRAujgUCWia9ftO5H17nAWgk11QcOjQvLFuR2SjbztJgHCVLvJkYgoIkATrZGDxtOtpATJ4AUdaGo0nRgs9mwCqushvFkqeOPJ6Z4pBTUGH7eti/UikAbDJr4qLS6d7SajA/cVT0p7IOgkFb78geTt507vlz1yhk8HP93ehX00Vffe1XXpizBrYVTEYf01gW1y22hB3j5zJMhzJDzKj+Id4EZUbkwsnvaMAjGVk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
